### ISSUE TITLE
Remove Raffles Institution (Secondary)

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#143]
Since students can choose from all schools when registering, we can remove Raffles Institution (Secondary) and just let students sign-up for Raffles Institution which is an integrated program like DHS, Hwa Chong, and a few others. That way, as they get older, they can stay in Raffles Institution.

**Comment by dinoboff** [comment]
@SingaporeClouds There are two resources listing the schools:
- https://singpath.firebaseio.com/classMentors/schools
- https://github.com/ChrisBoesch/singpathfire/blob/master/src/shared/components/schools/schools.js

I think you wanted to use the firebase list only so that they can be shared with other apps (like stats).

Is the firebase list accurate and can I change the crest paths from '../assets/crests/tempbadge.png' to '/assets/crests/tempbadge.png'?

The crests will be hosted at https://github.com/ChrisBoesch/singpathfire/tree/master/src/assets/crests
(I will remove the school folder).

They will also be copied and saved in the backend repo as part of the dev/deploy process, but the canonical src will be https://github.com/ChrisBoesch/singpathfire/tree/master/src/assets/crests

**Comment by dinoboff** [comment]
@SingaporeClouds Also, is it possible to rename the "crest" key to "iconUrl" and "group" to "type". That's how a school is saved in the a user profile? 

I can migrate the profile data to different schema if it's an issue.

**Comment by SingaporeClouds** [comment]
Hi Damien,

All of these changes sound fine to me. Please double check that everything
is still working properly after you make migrations since the Ace of Coder
event is ongoing.

I will be running a class on Tuesday evening my time from 5pm to 8pm. So
things need to be stable during that specific time.

On Sun, Aug 9, 2015 at 11:16 PM, Damien Lebrun <notifications@github.com>
wrote:

> @SingaporeClouds <https://github.com/SingaporeClouds> Also, is it
> possible to rename the "crest" key to "iconUrl" and "group" to "type".
> That's how a school is saved in the a user profile?
>
> I can migrate the profile data to different schema if it's an issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/143#issuecomment-129197788>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University
